@BookingApp.Api_HostAddress = http://localhost:5149

###
POST {{BookingApp.Api_HostAddress}}/api/Auth/register
Content-Type: application/json
Accept: application/json

{
  "email": "test@example.com",
  "password": "Test123!",
  "fullName": "Test User",
  "role": "Customer"
}
